### ISSUE TITLE
Grid Column format displays UTC as GMT+1

### ISSUE THREAD

**Issue by Kolokial** [telerik/kendo-intl#73]
The server is giving me an ISO8601 formatted date string `2019-07-08T15:43:17.457Z` which I am then putting into a `new Date()`. Kendo's Grid Column formats the date according to the `format` attribute below, but the date displayed is GMT. I would like to display the UTC time.

    <kendo-grid-column
            field="Created"
            format="{0:yyyy/MM/dd HH:mm:ss}"
            [sortable]="false"
            width="130"
        >

**Comment by danielkaradachki** [comment]
The repository is for bug reports only regarding the intl package. For issues with the angular components, please open an issue in the [kendo-angular](https://github.com/telerik/kendo-angular/issues) repo with runnable sample that demonstrates it. If the problem is with configuring the Grid, please open a [support ticket](https://www.telerik.com/account/support-tickets).
